CREATE SCHEMA base_datos;
USE base_datos;

CREATE TABLE users (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
email VARCHAR (200) NOT NULL, 
usuario VARCHAR (150),
contrasena VARCHAR (255) NOT NULL, 
fecha_nacimiento DATE NOT NULL, 
dni INT UNSIGNED NOT NULL, 
createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
deletedAt TIMESTAMP NULL
);

CREATE TABLE productos (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
usuario_id INT UNSIGNED NOT NULL,
nombre_producto VARCHAR (100), 
descripcion VARCHAR (300),
FOREIGN KEY (usuario_id) REFERENCES users(id),
createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
deletedAt TIMESTAMP NULL
);

CREATE TABLE comentarios (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
usuario_id INT UNSIGNED NOT NULL,
productos_id INT UNSIGNED NOT NULL, 
comentario VARCHAR (500),
FOREIGN KEY (usuario_id) REFERENCES users(id),
FOREIGN KEY (productos_id) REFERENCES productos(id),
createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
deletedAt TIMESTAMP NULL
);







